// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: directorydata.proto

#ifndef PROTOBUF_directorydata_2eproto__INCLUDED
#define PROTOBUF_directorydata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace posixok {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_directorydata_2eproto();
void protobuf_AssignDesc_directorydata_2eproto();
void protobuf_ShutdownFile_directorydata_2eproto();

class DirectoryEntry;
class DirectoryData;

enum DirectoryEntry_Type {
  DirectoryEntry_Type_ADD = 1,
  DirectoryEntry_Type_SUB = 2
};
bool DirectoryEntry_Type_IsValid(int value);
const DirectoryEntry_Type DirectoryEntry_Type_Type_MIN = DirectoryEntry_Type_ADD;
const DirectoryEntry_Type DirectoryEntry_Type_Type_MAX = DirectoryEntry_Type_SUB;
const int DirectoryEntry_Type_Type_ARRAYSIZE = DirectoryEntry_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* DirectoryEntry_Type_descriptor();
inline const ::std::string& DirectoryEntry_Type_Name(DirectoryEntry_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    DirectoryEntry_Type_descriptor(), value);
}
inline bool DirectoryEntry_Type_Parse(
    const ::std::string& name, DirectoryEntry_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DirectoryEntry_Type>(
    DirectoryEntry_Type_descriptor(), name, value);
}
// ===================================================================

class DirectoryEntry : public ::google::protobuf::Message {
 public:
  DirectoryEntry();
  virtual ~DirectoryEntry();

  DirectoryEntry(const DirectoryEntry& from);

  inline DirectoryEntry& operator=(const DirectoryEntry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DirectoryEntry& default_instance();

  void Swap(DirectoryEntry* other);

  // implements Message ----------------------------------------------

  DirectoryEntry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DirectoryEntry& from);
  void MergeFrom(const DirectoryEntry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef DirectoryEntry_Type Type;
  static const Type ADD = DirectoryEntry_Type_ADD;
  static const Type SUB = DirectoryEntry_Type_SUB;
  static inline bool Type_IsValid(int value) {
    return DirectoryEntry_Type_IsValid(value);
  }
  static const Type Type_MIN =
    DirectoryEntry_Type_Type_MIN;
  static const Type Type_MAX =
    DirectoryEntry_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    DirectoryEntry_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return DirectoryEntry_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return DirectoryEntry_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return DirectoryEntry_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int64 req_version = 2;
  inline bool has_req_version() const;
  inline void clear_req_version();
  static const int kReqVersionFieldNumber = 2;
  inline ::google::protobuf::int64 req_version() const;
  inline void set_req_version(::google::protobuf::int64 value);

  // optional .posixok.DirectoryEntry.Type type = 3 [default = ADD];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::posixok::DirectoryEntry_Type type() const;
  inline void set_type(::posixok::DirectoryEntry_Type value);

  // @@protoc_insertion_point(class_scope:posixok.DirectoryEntry)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_req_version();
  inline void clear_has_req_version();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::int64 req_version_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_directorydata_2eproto();
  friend void protobuf_AssignDesc_directorydata_2eproto();
  friend void protobuf_ShutdownFile_directorydata_2eproto();

  void InitAsDefaultInstance();
  static DirectoryEntry* default_instance_;
};
// -------------------------------------------------------------------

class DirectoryData : public ::google::protobuf::Message {
 public:
  DirectoryData();
  virtual ~DirectoryData();

  DirectoryData(const DirectoryData& from);

  inline DirectoryData& operator=(const DirectoryData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DirectoryData& default_instance();

  void Swap(DirectoryData* other);

  // implements Message ----------------------------------------------

  DirectoryData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DirectoryData& from);
  void MergeFrom(const DirectoryData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .posixok.DirectoryEntry entries = 1;
  inline int entries_size() const;
  inline void clear_entries();
  static const int kEntriesFieldNumber = 1;
  inline const ::posixok::DirectoryEntry& entries(int index) const;
  inline ::posixok::DirectoryEntry* mutable_entries(int index);
  inline ::posixok::DirectoryEntry* add_entries();
  inline const ::google::protobuf::RepeatedPtrField< ::posixok::DirectoryEntry >&
      entries() const;
  inline ::google::protobuf::RepeatedPtrField< ::posixok::DirectoryEntry >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:posixok.DirectoryData)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::posixok::DirectoryEntry > entries_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_directorydata_2eproto();
  friend void protobuf_AssignDesc_directorydata_2eproto();
  friend void protobuf_ShutdownFile_directorydata_2eproto();

  void InitAsDefaultInstance();
  static DirectoryData* default_instance_;
};
// ===================================================================


// ===================================================================

// DirectoryEntry

// required string name = 1;
inline bool DirectoryEntry::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DirectoryEntry::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DirectoryEntry::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DirectoryEntry::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& DirectoryEntry::name() const {
  return *name_;
}
inline void DirectoryEntry::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void DirectoryEntry::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void DirectoryEntry::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DirectoryEntry::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* DirectoryEntry::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void DirectoryEntry::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 req_version = 2;
inline bool DirectoryEntry::has_req_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DirectoryEntry::set_has_req_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DirectoryEntry::clear_has_req_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DirectoryEntry::clear_req_version() {
  req_version_ = GOOGLE_LONGLONG(0);
  clear_has_req_version();
}
inline ::google::protobuf::int64 DirectoryEntry::req_version() const {
  return req_version_;
}
inline void DirectoryEntry::set_req_version(::google::protobuf::int64 value) {
  set_has_req_version();
  req_version_ = value;
}

// optional .posixok.DirectoryEntry.Type type = 3 [default = ADD];
inline bool DirectoryEntry::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DirectoryEntry::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DirectoryEntry::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DirectoryEntry::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::posixok::DirectoryEntry_Type DirectoryEntry::type() const {
  return static_cast< ::posixok::DirectoryEntry_Type >(type_);
}
inline void DirectoryEntry::set_type(::posixok::DirectoryEntry_Type value) {
  assert(::posixok::DirectoryEntry_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// -------------------------------------------------------------------

// DirectoryData

// repeated .posixok.DirectoryEntry entries = 1;
inline int DirectoryData::entries_size() const {
  return entries_.size();
}
inline void DirectoryData::clear_entries() {
  entries_.Clear();
}
inline const ::posixok::DirectoryEntry& DirectoryData::entries(int index) const {
  return entries_.Get(index);
}
inline ::posixok::DirectoryEntry* DirectoryData::mutable_entries(int index) {
  return entries_.Mutable(index);
}
inline ::posixok::DirectoryEntry* DirectoryData::add_entries() {
  return entries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::posixok::DirectoryEntry >&
DirectoryData::entries() const {
  return entries_;
}
inline ::google::protobuf::RepeatedPtrField< ::posixok::DirectoryEntry >*
DirectoryData::mutable_entries() {
  return &entries_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace posixok

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::posixok::DirectoryEntry_Type>() {
  return ::posixok::DirectoryEntry_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_directorydata_2eproto__INCLUDED
